<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'object',
        'object_id',
        'oracle_id',
        'multiverse_ids',
        'mtgo_id',
        'tcgplayer_id',
        'cardmarket_id',
        'name',
        'lang',
        'released_at',
        'uri',
        'scryfall_uri',
        'layout',
        'highres_image',
        'image_status',
        'art_crop',
        'normal',
        'mana_cost',
        'cmc',
        'type_line',
        'oracle_text',
        'power',
        'toughness',
        'colors',
        'color_identity',
        'keywords',
        'legalities',
        'games',
        'reserved',
        'foil',
        'nonfoil',
        'finishes',
        'oversized',
        'promo',
        'reprint',
        'variation',
        'set_id',
        'set',
        'set_type',
        'set_uri',
        'set_search_uri',
        'scryfall_set_uri',
        'rulings_uri',
        'prints_search_uri',
        'collector_number',
        'digital',
        'rarity',
        'card_back_id',
        'artist',
        'artist_ids',
        'illustration_id',
        'border_color',
        'frame',
        'frame_effects',
        'full_art',
        'textless',
        'booster',
        'story_spotlight',
        'promo_types',
        'edhrec_rank',
        'penny_rank',
        'preview',
        'prices',
        'related_uris',
        'purchase_uris',
    ];
}
